django/Fantom/Fantom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/Fantom/posts/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('detail/<int:pk>/<slug:slug>', PostDetail.as_view(), name='detail'),
    path('post-update/<int:pk>/<slug:slug>', UpdatePostView.as_view(), name='post_update'),
    path('category/<int:pk>/<slug:slug>', CategoryDetail.as_view(), name='category_detail'),
    path('tag/<slug:slug>', TagDetail.as_view(), name='tag_detail'),
    path('post-create/', CreatePostView.as_view(), name='create_post'),
    path('post-delete/<int:pk>/<slug:slug>', DeletePostView.as_view(), name='post_delete'),
    path('search/', SearchView.as_view(), name='search'),
]

django/Fantom/users/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as authViews

app_name = "users"
urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('myprofile/', UserProfileView.as_view(), name='myprofile'),
    path('<int:pk>/', UserPostView.as_view(), name='user_posts'),
    path('update-profile/<slug:slug>', UserProfileUpdateView.as_view(), name='update_profile'),
    path('password-change/', authViews.PasswordChangeView.as_view(), name='password_change'),
    path('password-change-done/', authViews.PasswordChangeDoneView.as_view(), name='password_change_done'),

]

django/Fantom/templates/base.html
{% load static %}
{% load custom_tags %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static "img/favicon.png" %}" type="image/png">
        <title>Fantom Blog</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "vendors/linericon/style.css" %}">
        <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
        <link rel="stylesheet" href="{% static "vendors/owl-carousel/owl.carousel.min.css" %}">
        <link rel="stylesheet" href="{% static "vendors/lightbox/simpleLightbox.css" %}">
        <link rel="stylesheet" href="{% static "vendors/nice-select/css/nice-select.css" %}">
        <link rel="stylesheet" href="{% static "vendors/animate-css/animate.css" %}">
        <link rel="stylesheet" href="{% static "vendors/jquery-ui/jquery-ui.css" %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        <link rel="stylesheet" href="{% static "css/responsive.css" %}">
    </head>
    <body>

        <!--================Header Menu Area =================-->
        <header class="header_area">
            {% include 'messages.html' %}
            <div class="logo_part">
            	<div class="container">
            		<a class="logo" href="{% url 'index' %}"><img src="{% static "img/logo.png" %}" alt=""></a>
            	</div>
            </div>
			<div class="main_menu">
				<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container">
						<!-- Brand and toggle get grouped for better mobile display -->
						<a class="navbar-brand logo_h" href="{% url 'index' %}"><img src="{% static "img/logo.png" %}" alt=""></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
							<ul class="nav navbar-nav menu_nav">
								<li class="nav-item active"><a class="nav-link" href="{% url 'index' %}">Ana Sayfa</a></li>

                                <li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">KATEGORİLER</a>
									<ul class="dropdown-menu">
                                        {% categories as categories %}
                                        {% for category in categories %}
                                        <li class="nav-item"><a class="nav-link" href="{% url 'category_detail' pk=category.id slug=category.slug %}"> {{ category.title }} </a></li>
                                        {% endfor %}
                                        </ul>

								<li class="nav-item"><a class="nav-link" href="{% url 'users:user_list' %}">KULLANICILAR</a></li>
                                {% if user.is_authenticated %}
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="{% url 'create_post' %}"> YAZI EKLE </a></li>
										<li class="nav-item"><a class="nav-link" href="{% url 'users:password_change' %}"> ŞİFRE DEĞİŞTİR </a></li>
										<li class="nav-item"><a class="nav-link" href="{% url 'users:myprofile' %}"> PROFİLİM </a></li>
										<li class="nav-item"><a class="nav-link" href="{% url 'users:logout' %}"> ÇIKIŞ YAP </a></li>
									</ul>
								</li>
                                {% else %}
								<li class="nav-item"><a class="nav-link" href="{% url 'users:login' %}"> GİRİŞ YAP </a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'users:register' %}"> KAYIT OL </a></li>
                                {% endif %}
                                <li class="nav-item"><a class="nav-link" href="#"> İLETİŞİM </a></li>
							</ul>
							<ul class="nav navbar-nav navbar-right ml-auto">
								<li class="nav-item"><a href="#" class="search"><i class="lnr lnr-magnifier"></i></a></li>
							</ul>
						</div>
					</div>
				</nav>
			</div>
        </header>
        <!--================Header Menu Area =================-->
    {% block content %}

    {% endblock %}

        <!--================ start footer Area  =================-->
        <footer class="footer-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3  col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">About Us</h6>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">Newsletter</h6>
                            <p>Stay updated with our latest trends</p>
                            <div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                    <div class="input-group d-flex flex-row">
                                        <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                        <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
                                    </div>
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-widget instafeed">
                            <h6 class="footer_title">Instagram Feed</h6>
                            <ul class="list instafeed d-flex flex-wrap">
                                <li><img src="{% static "img/instagram/Image-01.jpg" %}" alt=""></li>
                                <li><img src="{% static "img/instagram/Image-02.jpg" %}" alt=""></li>
                                <li><img src="{% static "img/instagram/Image-03.jpg" %}" alt=""></li>
                                <li><img src="{% static "img/instagram/Image-04.jpg" %}" alt=""></li>
                                <li><img src="{% static "img/instagram/Image-05.jpg" %}" alt=""></li>
                                <li><img src="{% static "img/instagram/Image-06.jpg" %}" alt=""></li>
                                <li><img src="{% static "img/instagram/Image-07.jpg" %}" alt=""></li>
                                <li><img src="{% static "img/instagram/Image-08.jpg" %}" alt=""></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-6 col-sm-6">
                        <div class="single-footer-widget f_social_wd">
                            <h6 class="footer_title">Follow Us</h6>
                            <p>Let us be social</p>
                            <div class="f_social">
                            	<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row footer-bottom d-flex justify-content-between align-items-center">
                    <p class="col-lg-12 footer-text text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
        </footer>
		<!--================ End footer Area  =================-->




        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static "js/jquery-3.2.1.min.js" %}"></script>
        <script src="{% static "js/popper.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/stellar.js" %}"></script>
        <script src="{% static "vendors/lightbox/simpleLightbox.min.js" %}"></script>
        <script src="{% static "vendors/nice-select/js/jquery.nice-select.min.js" %}"></script>
        <script src="{% static "vendors/isotope/imagesloaded.pkgd.min.js" %}"></script>
        <script src="{% static "vendors/isotope/isotope-min.js" %}"></script>
        <script src="{% static "vendors/owl-carousel/owl.carousel.min.js" %}"></script>
        <script src="{% static "vendors/jquery-ui/jquery-ui.js" %}"></script>
        <script src="{% static "js/jquery.ajaxchimp.min.js" %}"></script>
        <script src="{% static "js/mail-script.js" %}"></script>
        <script src="{% static "js/theme.js" %}"></script>
    </body>
</html>

django/Fantom/templates/messages.html
{% if messages %}

    {% for message in messages %}
<div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">x</button>
    {{ message }}
    </div>
    {% endfor %}

{% endif %}

django/Fantom/templates/right_side.html
{% load static %}
{% load custom_tags %}

<div class="col-lg-4">
                        <div class="blog_right_sidebar">
                            <aside class="single_sidebar_widget search_widget">
                                <form action="{% url 'search' %}" method="get">
                                    <div class="input-group">
                                    <input type="text" class="form-control" placeholder="Search Posts" name="q">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="button"><i class="lnr lnr-magnifier"></i></button>
                                    </span>
                                </div><!-- /input-group -->
                                </form>
                                <div class="br"></div>
                            </aside>
                            <aside class="single_sidebar_widget author_widget">
                                <img class="author_img rounded-circle" src="{% static "img/blog/author.png" %}" alt="">
                                <h4>Charlie Barber</h4>
                                <p>Senior blog writer</p>
                                <div class="social_icon">
                                    <a href="#"><i class="fa fa-facebook"></i></a>
                                    <a href="#"><i class="fa fa-twitter"></i></a>
                                    <a href="#"><i class="fa fa-github"></i></a>
                                    <a href="#"><i class="fa fa-behance"></i></a>
                                </div>
                                <p>Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.</p>
                                <div class="br"></div>
                            </aside>
                            <aside class="single_sidebar_widget popular_post_widget">
                                <h3 class="widget_title">Popular Posts</h3>
                                {% hit_posts as posts %}
                                {% for post in posts %}
                                <div class="media post_item">
                                    <img src="{{ post.image.url }}" alt="post" style="width:100px; height:60px">
                                    <div class="media-body">
                                        <a href="{% url 'detail' pk=post.pk slug=post.slug %}"><h3>{{ post.title }}</h3></a>
                                        <p>Hit: {{ post.hit }}</p>
                                    </div>
                                </div>
                                {% endfor %}
                                <div class="br"></div>
                            </aside>
                            <aside class="single_sidebar_widget">
                                <a href="#"><img class="img-fluid" src="{% static "img/blog/add.jpg" %}" alt=""></a>
                                <div class="br"></div>
                            </aside>
                            <aside class="single_sidebar_widget post_category_widget">
                                <h4 class="widget_title">Post Categories</h4>
                                <ul class="list cat-list">
                                    {% categories as categories %}
                                    {% for category in categories %}
                                    <li>
                                        <a href="{% url 'category_detail' pk=category.id slug=category.slug %}" class="d-flex justify-content-between">
                                            <p>{{ category.title }}</p>
                                            <p>{{ category.post_count }}</p>
                                        </a>
                                    </li>
                                    {% endfor %}

                                </ul>
                                <div class="br"></div>
                            </aside>
                            <aside class="single-sidebar-widget tag_cloud_widget">
                                <h4 class="widget_title">Tag Clouds</h4>
                                <ul class="list">
                                    {% tags as etiketler %}
                                    {% for etiket in etiketler %}
                                    <li><a href="{% url 'tag_detail' etiket.slug %}">{{ etiket }}</a></li>
                                    {% endfor %}
                                </ul>
                            </aside>
                        </div>
                    </div>