django/Fantom/Fantom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('users/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/Fantom/posts/urls.py
from django.urls import path, include
from .views import *


urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('detail/<int:pk>/<slug:slug>', PostDetail.as_view(), name='detail'),
    path('post-update/<int:pk>/<slug:slug>', UpdatePostView.as_view(), name='post_update'),
    path('category/<int:pk>/<slug:slug>', CategoryDetail.as_view(), name='category_detail'),
    path('tag/<slug:slug>', TagDetail.as_view(), name='tag_detail'),
    path('post-create/', CreatePostView.as_view(), name='create_post'),
    path('post-delete/<int:pk>/<slug:slug>', DeletePostView.as_view(), name='post_delete'),
    path('search/', SearchView.as_view(), name='search'),
]

django/Fantom/users/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth import views as authViews

app_name = "users"
urlpatterns = [
    path('', UserListView.as_view(), name='user_list'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('myprofile/', UserProfileView.as_view(), name='myprofile'),
    path('<int:pk>/', UserPostView.as_view(), name='user_posts'),
    path('update-profile/<slug:slug>', UserProfileUpdateView.as_view(), name='update_profile'),
    path('password-change/', authViews.PasswordChangeView.as_view(), name='password_change'),
    path('password-change-done/', authViews.PasswordChangeDoneView.as_view(), name='password_change_done'),

]

django/Fantom/users/models.py
from django.db import models
from django.conf import settings
from django.template.defaultfilters import slugify
from PIL import Image
from django.db.models.signals import post_save


class UserProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    birth_day = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=10000, blank=True)
    image = models.ImageField(blank=True, null=True, default='users/django.png', upload_to='users', max_length=250)
    slug = models.SlugField(unique=True, editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.user.username)
        super(UserProfile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 200 or img.width > 200:
            new_size = (200, 200)
            img.thumbnail(new_size)
            img.save(self.image.path)

        def __str__(self):
            return self.user.username


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(create_user_profile, sender=settings.AUTH_USER_MODEL)

django/Fantom/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit
from .models import *


class RegisterForm(UserCreationForm):
    username = forms.CharField()
    email = forms.EmailField(max_length=50)
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.field_class = 'mt-10'
        self.helper.layout = Layout(
            Field("birth_day", css_class="single-input"),
            Field("bio", css_class="single-input"),
            Field("image", css_class="single-input"),
        )

        self.helper.add_input(Submit('submit', 'Update', css_class="genric-btn success-border medium"))

    class Meta:
        model = UserProfile
        fields = ('birth_day',
                  'bio',
                  'image')
        widgets = {
            'birth_day': forms.DateInput(attrs={'type': 'date'})
        }

django/Fantom/users/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, UpdateView, ListView
from .forms import RegisterForm, UserProfileForm
from .models import UserProfile
from posts.models import Post


class RegisterView(CreateView):
    template_name = 'users/register.html'
    form_class = RegisterForm
    success_url = '/'


class UserLogin(LoginView):
    template_name = 'users/login.html'


class UserLogout(LogoutView):
    template_name = 'users/login.html'


@method_decorator(login_required(login_url='users/login'), name='dispatch')
class UserProfileUpdateView(SuccessMessageMixin, UpdateView):
    model = UserProfile
    template_name = 'users/profile-update.html'
    form_class = UserProfileForm
    success_message = "Kullanıcı profili başarılı bir şekilde güncellendi!"

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(UserProfileUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('users:update_profile', kwargs={'slug': self.object.slug})

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect('/')
        return super(UserProfileUpdateView, self).get(self, request, *args, **kwargs)


@method_decorator(login_required(login_url='users/login'), name='dispatch')
class UserProfileView(ListView):
    template_name = 'users/my-profile.html'
    model = Post
    context_object_name = 'userposts'
    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)
        context['userprofile'] = UserProfile.objects.get(user=self.request.user)
        return context

    def get_queryset(self):
        return Post.objects.filter(user=self.request.user).order_by('-id')


class UserPostView(ListView):
    template_name = 'users/user-posts.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        return Post.objects.filter(user=self.kwargs['pk'])


class UserListView(ListView):
    template_name = 'users/user-list.html'
    model = UserProfile
    context_object_name = 'users'
    paginate_by = 4

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        return context

django/Fantom/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Register</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">{{ category.title }}</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        {% if not user.is_authenticated %}
						<h2 style="text-align:center;color:#00FFFF">Login</h2>
                            <form method="post">
                            {% csrf_token %}
                            {% if form.errors %}
                             <div id="errors">
                                 <div class="inner">
                                     <p style="color:red">Lütfen aşağıdaki hataları kontrol edin.</p>
                                     <ul>
                                         {% for field in form %}
                                         {% if field.errors %}
                                         <li>{{ field.label }}: {{ field.errors | striptags }}</li>
                                         {% endif %}
                                         {% endfor %}
                                     </ul>
                                 </div>

                             </div>
                                {% endif %}

							<div class="mt-10">
                                <input type="text" name="username" placeholder="Kullanıcı Adı" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Kullanıcı Adı'" required="" class="single-input">
                            </div>

                            <div class="mt-10">
                                <input type="password" name="password" placeholder="Şifre" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Şifre'" required="" class="single-input">
                            </div>

                            <button type="submit" class="genric-btn success circle" style="float:right;margin-top:30px">Login</button>
                            </form>
                        {% else %}
                        <h2 style="color:red">Daha önceden giriş yaptınız</h2>
                        {% endif %}
                        </div>

                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
        {% endblock %}

django/Fantom/templates/users/my-profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2 style="margin-top:30px">Profilim</h2>
						<div class="page_link">
							<img src="{{ userprofile.image.url }}">
							<h4 style="color:white">Kullanıcı Adı: {{ userprofile.user.username|title }}</h4>
							<h4 style="color:white">Doğum Tahihi: {{ userprofile.birth_day }}</h4>
							<h4 style="color:white">Hakkında: {{ userprofile.bio|linebreaks }}</h4>
							<a href="{% url 'users:update_profile' slug=userprofile.slug %}" class="genric-btn info circle" style="margin-bottom:30px">Güncelle</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar">

                            {% for post in userposts %}
                            <article class="blog_style1">
                            	<div class="blog_img">
                            		<img class="img-fluid" src="{{ post.image.url }}" alt="">
                            	</div>
                            	<div class="blog_text">
									<div class="blog_text_inner">
										{% for tag in post.tag.all %}
										<a class="cat" href="{% url 'tag_detail' tag.slug %}">{{ tag.title }}</a>
										{% endfor %}
										<a href="{% url 'detail' pk=post.id slug=post.slug %}"><h4>{{ post.title }}</h4></a>
										<p>{{ post.content | truncatechars:175 }}</p>
										<div class="date">
											<a href="#"><i class="fa fa-calendar" aria-hidden="true"></i>{{ post.publishing_date }}</a>
											<a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>
										</div>	
									</div>
                            	</div>
                            </article>

                            {% endfor %}


                            {% if is_paginated %}
                            <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
									{% if page_obj.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
									{% for i in paginator.page_range %}
									{% if page_obj.number == i %}

		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									{% endfor %}
									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}
                        </div>
                    </div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
        {% endblock %}

django/Fantom/templates/users/profile-update.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Profili Güncelle</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">{{ category.title }}</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
						<h2 style="text-align:center;color:#00FFFF">Profili Güncelle</h2>
                                {% crispy form %}
                        </div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--===============Blog Area =================-->
        {% endblock %}

django/Fantom/templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Register</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">{{ category.title }}</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
						<h2 style="text-align:center;color:#00FFFF">Register</h2>
                            <form method="post">
                            {% csrf_token %}
                            {% if form.errors %}
                             <div id="errors">
                                 <div class="inner">
                                     <p style="color:red">Lütfen aşağıdaki hataları kontrol edin.</p>
                                     <ul>
                                         {% for field in form %}
                                         {% if field.errors %}
                                         <li>{{ field.label }}: {{ field.errors | striptags }}</li>
                                         {% endif %}
                                         {% endfor %}
                                     </ul>
                                 </div>

                             </div>
                                {% endif %}

                        <div class="blog_left_sidebar">
							<div class="mt-10">
                                <input type="text" name="username" placeholder="Kullanıcı Adı" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Kullanıcı Adı'" required="" class="single-input">
                            </div>
                            <div class="mt-10">
                                <input type="text" name="email" placeholder="Email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email'" required="" class="single-input">
                            </div>
                            <div class="mt-10">
                                <input type="password" name="password1" placeholder="Şifre" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Şifre'" required="" class="single-input">
                            </div>
                            <div class="mt-10">
                                <input type="password" name="password2" placeholder="Şifre Tekrar" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Şifre Tekrar'" required="" class="single-input">
                            </div>
                            <button type="submit" class="genric-btn success circle" style="float:right;margin-top:30px">Register</button>
                            </form>
                        </div>
                        </div>

                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
        {% endblock %}

django/Fantom/templates/users/user-list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Kullanıcılar</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar" style="text-align:center">

                            {% for user in users %}

                            <div class="container" style="border-style:solid;border-width:2px;border-color:green;margin-bottom:5px">
                              <img src="{{ user.image.url }}" style="margin-top:10px">
                              <a href="{% url 'users:user_posts' pk=user.user.pk %}"><h4>{{ user.user.username }}</h4></a>
                              <p>Hakkında: {{ user.bio|linebreaks }}</p>
                              <p>Doğum Günü: {{ user.birth_day }}</p>

                            </div>

                            {% endfor %}

                            {% if is_paginated %}

                            <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
									{% if page_obj.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
									{% for i in paginator.page_range %}
									{% if page_obj.number == i %}

		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									{% endfor %}
									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}
                        </div>
                    </div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
        {% endblock %}

django/Fantom/templates/users/user-posts.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2> {{ user.username|title }} Kullanıcısının Postları</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar">

                            {% for post in posts %}
                            <article class="blog_style1">
                            	<div class="blog_img">
                            		<img class="img-fluid" src="{{ post.image.url }}" alt="">
                            	</div>
                            	<div class="blog_text">
									<div class="blog_text_inner">
										{% for tag in post.tag.all %}
										<a class="cat" href="{% url 'tag_detail' tag.slug %}">{{ tag.title }}</a>
										{% endfor %}
										<a href="{% url 'detail' pk=post.id slug=post.slug %}"><h4>{{ post.title }}</h4></a>
										<p>{{ post.content | truncatechars:175 }}</p>
										<div class="date">
											<a href="#"><i class="fa fa-calendar" aria-hidden="true"></i>{{ post.publishing_date }}</a>
											<a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>
										</div>	
									</div>
                            	</div>
                            </article>

                            {% endfor %}


                            {% if is_paginated %}
                            <nav class="blog-pagination justify-content-center d-flex">
		                        <ul class="pagination">
									{% if page_obj.has_previous %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
									{% for i in paginator.page_range %}
									{% if page_obj.number == i %}

		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									{% endfor %}
									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}
                        </div>
                    </div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
        {% endblock %}